title: Introducción a la IA
description: Repositorio del curso Introducción a la IA
theme: jekyll-theme-minimal
url: "https://ArnulfoPerez.github.io"
baseurl: "" # Leave empty unless your site is in a subdirectory
